### PR TITLE
Feature/bids commerce

### PR DESCRIPTION
**Pull request by LautaroNovolabs**
## Description
This pr add views and services to commerce with bids seller side and part of buyer side.
This PR also add View and Edition of the profile 

## Proposed changes
Interface change of bid to accept one
Interface of restaurants name

## More information
image
image
image
image
image
image

### CODE REVIEW

**Comment by totigm** [comment]
tenes conflicts campeón

**Comment by mati-novolabs** [comment]
Hay quilombo en el build ademas de los conflicts

**Review by mati-novolabs — CHANGES_REQUESTED** [review]
fix error in build

**Comment by LautaroNovolabs** [comment]
Sii, pero mande el pr antes de lo debido por confusion, pq falta l ode las bids del comprador, que esta el cho el fron pero n oel vac ni la conecxion xdxd

**Comment by LautaroNovolabs** [comment]
mala mia

**Pull request merged**
